- hosts: all
  become: true
  tasks:
    - name: update
      apt:
        update_cache: true
- hosts: db
  become: true
  tasks:
    - name: install apache2 
      tags: apache2
      apt:
        name:
          - "{{ apache_package_name }}"
          - "{{ php_package_name }}"
    - name: copy file
      tags: copy
      copy:
        src: default.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
    - name: start service http
      service:
        name: apache2
        state: started
        