mysql_root_password: tinh
mysql_databases:
  - name: example_db
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: example_user
    password: tqt
    priv: "example_db.*:ALL"